### PR TITLE
Update AquaOS.c

### PR DESCRIPTION
**Pull request by Faimue**
@Accelium check and review

### CODE REVIEW

**Review by Real-Troglodyte — COMMENTED** [review]
This appears to be a invalid change. Will review further until making final decision

**Comment by Faimue** [comment]
Self-error

Pull requests denied

**Review by Faimue — COMMENTED** [review]
Removed conflicting files by deleting code lines 13-18 of the AquaOS file

**Comment by Faimue** [comment]
@Accelium here!

**Pull request merged**
